export const categoriesHeader = [
  "Cultural and Historical Interests",
  "Entertainment and Leisure",
  "Wellness and Relaxation",
  "Sports and Recreation",
  "Outdoors and Nature",
  "Shopping Experiences",
  "Travel and Transportation",
  "Different Restaurant types and Cuisines",
  "Snacks, Beverage and Deserts",
  "Unique Dining Experiences",
  "Religious and Spiritual Sites",
  "Specialized Interest",
];

export const categories = {
  "Cultural and Historical Interests": [
    { name: "Museums", code: "10027" },
    { name: "Castle", code: "16011" },
    { name: "Historic and Protected Site", code: "16020" },
    { name: "Monument", code: "16026" },
    { name: "Palace", code: "16031" },
  ],
  "Entertainment and Leisure": [
    { name: "Amusement Park", code: "10001" },
    { name: "Aquarium", code: "10002" },
    { name: "Art Gallery", code: "10004" },
    { name: "Escape Room", code: "10015" },
    { name: "Concert Hall", code: "10037" },
    { name: "Zoo", code: "10056" },
    { name: "Water Park", code: "10055" },
  ],
  "Wellness and Relaxation": [
    { name: "Massage Clinic", code: "11070" },
    { name: "Spa", code: "11073" },
    { name: "Tea Room", code: "13036" },
    { name: "Yoga Studio", code: "18028" },
    { name: "Park", code: "16039" },
  ],
  "Sports and Recreation": [
    { name: "Skydiving Center", code: "18057" },
    { name: "Ski Resort and Area", code: "18061" },
    { name: "Water Sports", code: "18067" },
    { name: "Hiking Trail", code: "18022" },
    { name: "Rock Climbing", code: "16044" },
    { name: "Go-Karting", code: "10019" },
    { name: "Golf Course", code: "18018" },
    { name: "Martial Arts Dojo", code: "18036" },
    { name: "Surf Spot", code: "16049" },
    { name: "Soccer Stadium", code: "10065" },
  ],
  "Outdoors and Nature": [
    { name: "Botanical Garden", code: "16005" },
    { name: "National Park", code: "16034" },
    { name: "Nature Preserve", code: "16028" },
    { name: "Scenic Lookout", code: "16046" },
    { name: "Beach", code: "16003" },
    { name: "Mountain", code: "16027" },
    { name: "Waterfall", code: "16052" },
  ],
  "Shopping Experiences": [
    { name: "Shopping Mall", code: "17114" },
    { name: "Souvenir Store", code: "17116" },
    { name: "Antique Store", code: "17002" },
    { name: "Book Store", code: "17018" },
    { name: "Flea Market", code: "17054" },
    { name: "Vintage and Thrift Store", code: "17138" },
    { name: "Art and Craft Store", code: "17003" },
  ],
  "Travel and Transportation": [
    { name: "Airport", code: "19031" },
    { name: "Bus Station", code: "19042" },
    { name: "Taxi Service", code: "19068" },
    { name: "Train Station", code: "19047" },
    { name: "Car Rental", code: "19048" },
  ],
  "Different Restaurant types and Cuisines": [
    { name: "Indian Restaurant", code: "13199" },
    { name: "Korean Restaurant", code: "13289" },
    { name: "Japanese Restaurant", code: "13263" },
    { name: "Indonesian Restaurant", code: "13225" },
    { name: "Chinese Restaurant", code: "13099" },
    { name: "Italian Restaurant", code: "11047" },
    { name: "Mexican Restaurant", code: "11049" },
    { name: "BBQ Joint", code: "13026" },
    { name: "Seafood", code: "13338" },
  ],
  "Snacks, Beverage and Deserts": [
    { name: "Coffe shops", code: "13035,13034" },
    { name: "Bakery", code: "13002" },
    { name: "Bar", code: "13003" },
    { name: "Pub", code: "13018" },
    { name: "Cafe", code: "13016" },
    { name: "Dessert Shop", code: "13040" },
    { name: "Ice Cream Shop", code: "13046" },
  ],
  "Unique Dining Experiences": [
    { name: "Winery", code: "13387" },
    { name: "Brewery", code: "13029" },
    { name: "Theme Restaurant", code: "13354" },
    { name: "Vineyard", code: "13386" },
    { name: "Sushi Restaurant", code: "13276" },
    { name: "Bubble Tea Shop", code: "13033" },
  ],
  "Religious and Spiritual Sites": [
    { name: "Church", code: "12101" },
    { name: "Mosque", code: "12106" },
    { name: "Temple", code: "12111" },
    { name: "Synagogue", code: "12110" },
    { name: "Sikh Temple", code: "12109" },
  ],
  "Specialized Interest": [
    { name: "Observatory", code: "12081" },
    { name: "Brewery", code: "13029" },
    { name: "Cannabis Store", code: "17021" },
    { name: "Street Art", code: "10059" },
  ],
};
